name: List changes
description: list changes relative to PR target or specified commit
inputs:
  base_branch:
    description: Base branch to show changes
    required: false
    default: master
  path:
    description: Show changes only inside path in repo
    required: false
    default: ''
  max_depth:
    description: limits max depth of output
    required: false
    default: 0
outputs:
  result:
    description: Array of strings, containing changed items
    value: ${{ steps.list.outputs.items }}
runs:
  using: "composite"
  steps:
    - id: list
      shell: bash
      env:
          TARGET_COMMIT: ${{ github.event.pull_request.base.sha && github.event.pull_request.base.sha || inputs.base_branch }}
      run: >
        jq -nc --arg items "$(
          git diff --name-only "$TARGET_COMMIT" |
          grep '${{ inputs.path }}' |
          awk -F'/' 'BEGIN { depth = ${{ inputs.max_depth }} } { for(i = 1; i < depth; ++i) { printf "%s/", $i }; print $depth }' |
          sort -u
        )" '$items | split("\n")' |
        (echo -n "::set-output name=items::" && cat)
